## app.R ##
library(shiny)
library(shinydashboard)
library(shinyjs)
library(tidyverse)
library(vroom)
library(janitor)
library(flextable)
library(colourpicker)
library(RColorBrewer)


colourschemes <- list('Greyscale' = c("#000000","#737373","#BDBDBD","#D9D9D9","#F0F0F0"),#"Greys",
                      'Accent' = c("#7FC97F","#BEAED4","#FDC086","#FFFF99","#386CB0","#F0027F","#BF5B17","#666666"),
                      'Dark2'= brewer.pal(n=8,name="Dark2"),
                      'Paired'=brewer.pal(n=8,name="Paired"),
                      "Set1" = brewer.pal(n=8,name="Set1"),
                      "Set2"=brewer.pal(n=8,name="Set2"),
                      "Set3"=brewer.pal(n=8,name="Set3"),
                      'Colour-blind friendly'=  c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7"),
                      'Custom'=c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7"))
themes <- list("Light" = theme_light(),"Minimal" = theme_minimal(),"Black/White" = theme_bw(),"Classic" = theme_classic(),"Gray"=theme_gray())
legend_positions <- list("No" = 'none',"Yes" = 'top')



#templates for available checklists
template_data <- NULL
template_data[['cheers']] = tibble(
  section = c('Title','Abstract','Introduction',rep('Methods',18),rep('Results',4),'Discussion',rep('Other information',2)),
  checklist_item = c(
    '1. Title',
    '2. Abstract',
    '3. Background and objectives',
    '4. Health economic analysis plan',
    '5. Study population',
    '6. Setting and location',
    '7. Comparators',
    '8. Perspective',
    '9. Time horizon',
    '10. Discount rate',
    '11. Selection of outcomes',
    '12. Measurement of outcomes',
    '13. Valuation of outcomes',
    '14. Measurement and valuation of resources and costs',
    '15. Currency, price date, and conversion',
    '16. Rationale and description of model',
    '17. Analytics and assumptions',
    '18. Characterizing heterogeneity',
    '19. Characterizing distributional effects',
    '20. Characterizing uncertainty',
    '21. Approach to engagement with patients and others affected by the study',
    '22. Study parameters',
    '23. Summary of main results',
    '24. Effect of uncertainty',
    '25. Effect of engagement with patients and others affected by the study',
    '26. Study findings, limitations, generalizability, and current knowledge',
    '27. Source of funding',
    '28. Conflicts of interest'))

template_data[['consort']] = tibble(
  section=c(rep('Title and Abstract',2),rep('Introduction',2),rep('Methods',17),rep('Results',10),rep('Discussion',3),rep('Other information',3)),
  checklist_item = c(
    '1a. Title and Abstract',
    '1b. Title and Abstract',
    '2a. Background and objectives',
    '2b. Background and objectives',
    '3a. Trial design',
    '3b. Trial design',
    '4a. Participants',
    '4b. Participants',
    '5. Interventions',
    '6a. Outcomes',
    '6b. Outcomes',
    '7a. Sample size',
    '7b. Sample size',
    '8a. Randomisation: Sequence generation',
    '8b. Randomisation: Sequence generation',
    '9. Allocation: concealment mechanism',
    '10. Implementation',
    '11a. Blinding',
    '11b. Blinding',
    '12a. Statistical methods',
    '12b. Statistical methods',
    '13a. Participant flow',
    '13b. Participant flow',
    '14a. Recruitment',
    '14b. Recruitment',
    '15. Baseline data',
    '16. Numbers analysed',
    '17a. Outcomes and estimation',
    '17b. Outcomes and estimation',
    '18. Ancillary analyses',
    '19. Harms',
    '20. Limitations',
    '21. Generalisability',
    '22. Interpretation',
    '23. Registration',
    '24. Protocol',
    '25. Funding'))

template_date[['prisma']] = tibble(
  section=c('Title','Abstract',rep('Introduction',2),rep('Methods',17),rep('Results',11),rep('Discussion',4),rep('Other information',6)),
  checklist_item=c(
    '1. Title',
    '2. Abstract',
    '3. Rationale',
    '4. Objectives',
    '5. Eligibility criteria',
    '6. Information sources',
    '7. Search strategy',
    '8. Selection process',
    '9. Data collection process',
    '10a. Data items',
    '10b. Data items',
    '11.Study risk of bias assessment',
    '12. Effect measures',
    '13a. Synthesis methods',
    '13b. Synthesis methods',
    '13c. Synthesis methods',
    '13d. Synthesis methods',
    '13e. Synthesis methods',
    '13f. Synthesis methods',
    '14. Reporting bias assessment',
    '15. Certainty assessment',
    '16a. Study selection',
    '16b. Study selection',
    '17. Study characteristics',
    '18. Risk of bias in studies',
    '19. Results of individual studies',
    '20a. Results of syntheses',
    '20b. Results of syntheses',
    '20c. Results of syntheses',
    '20d. Results of syntheses',
    '21. Reporting biases',
    '22. Certainty of evidence',
    '23a. Discussion',
    '23b. Discussion',
    '23c. Discussion',
    '23d. Discussion',
    '24a. Registration and protocol',
    '24b. Registration and protocol',
    '24c. Registration and protocol',
    '25. Support',
    '26. Competing interests',
    '27. Availability of data, code and other materials'))

template_data[['prisma scr']] = tibble(
  section = c('Title','Abstract',rep('Introduction',2),rep('Methods',9),rep('Results',5),rep('Discussion',3),'Funding'),
  checklist_item = c(
    '1. Title',
    '2. Structured summary',
    '3. Rationale',
    '4. Objectives',
    '5. Protocol and registration',
    '6. Eligibility criteria',
    '7. Information sources',
    '8. Search',
    '9. Selection of sources of evidence',
    '10. Data charting process',
    '11. Data items',
    '12. Critical appraisal of individual sources of evidence',
    '13. Synthesis of results',
    '14. Selection of sources of evidence',
    '15. Characteristics of sources of evidence',
    '16. Critical appraisal within sources of evidence',
    '17. Results of individual sources of evidence',
    '18. Sythesis of results',
    '19. Summary of evidence',
    '20. Limitations',
    '21. Conclusions',
    '22. Funding'))

template_data[['probast']] = tibble(
  section = c(rep('Risk of bias',rep('Applicability',3),rep('Overall',2))),
  checklist_item = c(
    '1. Participants',
    '2. Predictors',
    '3. Outcome',
    '4. Analysis',
    '5. Participants',
    '6. Predictors',
    '7. Outcome',
    '8. Risk of bias',
    '9. Applicability'))

template_data[['spirit']] = tibble(
  section = c(rep('Administrative information',9),rep('Introduction',4),rep('Methods: Participants, interventions, and outcomes',10),rep('Methods: Assignment of interventions',4),rep('Methods: Data collection, management and analysis',6),rep('Methods: Monitoring',4),rep('Ethics and dissemination',11),rep('Appendices',2)),
  checklist_item = c(
    '1. Title',
    '2a. Trial registration',
    '2b. Trial registration',
    '3. Protocol version',
    '4. Funding',
    '5a. Roles and responsibilities',
    '5b. Roles and responsibilities',
    '5c. Roles and responsibilities',
    '5d. Roles and responsibilities',
    '6a. Background and rationale',
    '6b. Background and rationale',
    '7. Objectives',
    '8. Trial design',
    '9. Study setting',
    '10. Eligibility criteria',
    '11a. Interventions',
    '11b. Interventions',
    '11c. Interventions',
    '11d. Interventions',
    '12. Outcomes',
    '13. Participant timeline',
    '14. Sample size',
    '15. Recruitment',
    '16a. Allocation sequence generation',
    '16b. Allocation concealment mechanism',
    '17a. Blinding',
    '17b. Blinding',
    '18a. Data collection methods',
    '18b. Data collection methods',
    '19. Data management',
    '20a. Statistical methods',
    '20b. Statistical methods',
    '20c. Statistical methods',
    '21a. Data monitoring',
    '21b. Data monitoring',
    '22. Harms',
    '23. Auditing',
    '24. Research ethics approval',
    '25. Protocol amendments',
    '26a. Consent or assent',
    '26b. Consent or assent',
    '27. Confidentiality',
    '28. Declarations of interest',
    '29. Access to data',
    '30. Ancillary and post-trial care',
    '31a. Dissemination policy',
    '31b. Dissemination policy',
    '31c. Dissemination policy',
    '32. Informed consent materials',
    '33. Biological specimens'))


template_data[['squire']] = tibble(
  section = c('Title','Abstract',rep('Introduction',4),rep('Methods',6),'Results',rep('Discussion',4),'Other information'),
  checklist_item = c(
    '1. Title',
    '2. Abstract',
    '3. Problem description',
    '4. Available knowledge',
    '5. Rationale',
    '6. Specific aims',
    '7. Context',
    '8. Intervention(s)',
    '9. Study of the intervention(s)',
    '10. Measures',
    '11. Analysis',
    '12. Ethical considerations',
    '13. Results',
    '14. Summary',
    '15. Interpretation',
    '16. Limitations',
    '17. Conclusions',
    '18. Funding'))

template_data[['srqr']] = tibble(
  section = c(rep('Title and Abstract',2),rep('Introduction',2),rep('Methods',11),rep('Results/findings',2),rep('Discussion',2),rep('Other',2)),
  checklist_item = c(
    '1. Title',
    '2. Abstract',
    '3. Problem formulation',
    '4. Purpose or research question',
    '5. Qualitative approach and research paradigm',
    '6. Researcher characteristics and reflexivity',
    '7. Context',
    '8. Sampling strategy',
    '9. Ethical issues pertaining to human subjects',
    '10. Data collection methods',
    '11. Data collection instruments and technologies',
    '12. Units of study',
    '13. Data processing',
    '14. Data analysis',
    '15. Techniques to enhance trustworthiness',
    '16. Synthesis and interpretation',
    '17. Links to empirical data',
    '18. Integration',
    '19. Limitations',
    '20. Conflicts of interest',
    '21. Funding'))


template_data[['stard']] = tibble(
  section = c('Title','Abstract',rep('Introduction',2),rep('Methods',17),rep('Results',8),rep('Discussion',2),rep('Other information',3)),
  checklist_item = c(
    '1. Title',
    '2. Abstract',
    '3. Introduction - background',
    '4. Intoduction - study objectives',
    '5. Study design',
    '6. Participants',
    '7. Participants',
    '8. Participants',
    '9. Participants',
    '10a. Test methods',
    '10b. Test methods',
    '11. Test methods',
    '12a. Test methods',
    '12b. Test methods',
    '13a. Test methods',
    '13b. Test methods',
    '14. Analysis',
    '15. Analysis',
    '16. Analysis',
    '17. Analysis',
    '18. Analysis',
    '19. Participants',
    '20. Participants',
    '21a. Participants',
    '21b. Participants',
    '22. Participants',
    '23. Test results',
    '24. Test results',
    '25. Test results',
    '26. Discussion',
    '27. Discussion',
    '28. Other information',
    '29. Other information',
    '30. Other information'))

template_data[['strobe']] = tibble(
  section = c(rep('Title and Abstract',2),rep('Introduction',2),rep('Methods',14),rep('Results',11),rep('Discussion',4),'Other information'),
  checklist_item = c(
    '1a. Study design in title/abstract',
    '1b. Abstract',
    '2. Background/rationale',
    '3. Objectives',
    '4. Study design',
    '5. Setting',
    '6a. Participants',
    '6b. Participants',
    '7. Variables',
    '8. Data sources/ measurement',
    '9. Bias',
    '10. Study size',
    '11. Quantitative variables',
    '12a. Statistical methods',
    '12b. Statistical methods',
    '12c. Statistical methods',
    '12d. Statistical methods',
    '12e. Statistical methods',
    '13a. Participants',
    '13b. Participants',
    '13c. Participants',
    '14a. Descriptive data',
    '14b. Descriptive data',
    '14c. Descriptive data',
    '15. Outcome data',
    '16a. Main results',
    '16b. Main results',
    '16c. Main results',
    '17. Other analyses',
    '18. Key results',
    '19. Limitations',
    '20. Interpretation',
    '21. Generalisability',
    '22. Funding'))


template_data[['tidier']] = tibble(
  section = c("Brief name","Why",rep("What",2),"Who provided","How","Where",rep("When and how much",4),"Tailoring","Modifications",rep("How well",2)),
  checklist_item =  c( "1. Brief name","2. Why","3. Materials","4. Procedures","5. Who provided","6. How","7. Where","8a. Intensity","8b. Frequency","8c. Session time","8d. Overall duration","9. Tailoring","10. Modifications","11. Planned","12. Actual")
)

template_data[['tripod']] = tibble(
  section = c(rep('Title and Abstract',2),rep('Introduction',2),rep('Methods',18),rep('Results',9),rep('Discussion',4),rep('Other information',2)),
  checklist_item = c(
    '1. Title',
    '2. Abstract',
    '3a. Background and objectives',
    '3b. Background and objectives',
    '4a. Source of data',
    '4b. Source of data',
    '5a. Participants',
    '5b. Participants',
    '5c. Participants',
    '6a. Outcome',
    '6b. Outcome',
    '7a. Predictors',
    '7b. Predictors',
    '8. Sample size',
    '9. Missing data',
    '10a. Statistical analysis methods',
    '10b. Statistical analysis methods',
    '10c. Statistical analysis methods',
    '10d. Statistical analysis methods',
    '10e. Statistical analysis methods',
    '11. Risk groups',
    '12. Development vs. validation',
    '13a. Participants',
    '13b. Participants',
    '13c. Participants',
    '14a. Model development',
    '14b. Model development',
    '15a. Model specification',
    '15b. Model specification',
    '16. Model performance',
    '17. Model-updating',
    '18. Limitations',
    '19a. Interpretation',
    '19b. Interpretation',
    '20. Implications',
    '21. Supplementary information',
    '22. Funding'))


template_data[['custom']] = tibble(
  section = c('Section 1 ',rep('Section 2'),2),
  checklist_item = c(
    '1. Checklist item 1',
    '2a. Checklist item 2a',
    '2b. Checklist item 2b',))


create_template = function(choose_template,indat=template_data){
  template_name = tolower(choose_template)
  out = indat[[template_name]] %>% add_column("Study 1"=NA,"Study 2"=NA)
  return(out)
}

