---
title: 'Visual reporting checklist'
author: "Nicole White, David Borg"
date: "`r Sys.Date()`"
output: html_document

bibliography: reflist.bib

---

<style type="text/css">
body{
font-size: 12pt;
font-family: "Arial";
.basic-styling td,
.basic-styling th {
border: 1px solid #999;
padding: 0.5rem;

}
</style>





```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(kableExtra)
library(RColorBrewer)
library(flextable)
```

Current versions of supported checklists and citation information can be found on the [EQUATOR network website](https://www.equator-network.org/reporting-guidelines/). 

A list of further references and resources is provided below:

#### Consolidated Health Economic Evaluation Reporting Standards (CHEERS)

* [Summary of 2022 checklist update](https://bmcmedicine.biomedcentral.com/articles/10.1186/s12916-021-02204-0) (@husereau2022)
* Example application - DHCRC review once published

#### Transparent Reporting of a multivariable prediction model for Individual Prognosis Or Diagnosis (TRIPOD)

* [Explanation and Elaboration](https://www.acpjournals.org/doi/10.7326/M14-0698) (@moons2015)
* [Example application](https://www.karger.com/Article/PDF/525727)(@parsons2022)

#### Prediction model Risk Of Bias ASsessment Tool (PROBAST)

* [Explanation and Elaboration](https://pubmed.ncbi.nlm.nih.gov/30596876/) (@moons2019)
* [Example application](https://www.bmj.com/content/369/bmj.m1328) (@wynants2020)


#### Strengthening the Reporting of Observational Studies in Epidemiology (STROBE)

* [Explanation and Elaboration](https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.0040297) (@vandenbrouckel2007)
* Example application?

#### Template for Intervention Description and Replication (TIDierR)

* [Main website](http://www.tidierguide.org/)
* [Example application](https://www.ahajournals.org/doi/10.1161/CIRCOUTCOMES.114.001381) (@abell2015)

### References
